version: "3"
services:
  mariadb11:
    container_name: mariadb11
    image: mariadb:11
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password-1234
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-script:/docker-entrypoint-initdb.d