version: "3"
services:
  sqlserver-2019:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver-2017
    ports:
      - "1433:1433"
    volumes:
      - ./db/data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
      - ./db/secrets:/var/opt/mssql/secrets
    # https://learn.microsoft.com/ja-jp/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2017#environment-variables
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password-1234
#      - MSSQL_PID=Developer
      - MSSQL_LCID=1041
#      - MSSQL_COLLATION=Japanese_CI_AS